require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityInAppReview', :path => '../../../node_modules/@capacitor-community/in-app-review'
  pod 'CapacitorFirebaseCrashlytics', :path => '../../../node_modules/@capacitor-firebase/crashlytics'
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorCamera', :path => '../../../node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../node_modules/@capacitor/haptics'
  pod 'CapacitorScreenOrientation', :path => '../../../node_modules/@capacitor/screen-orientation'
  pod 'CapacitorShare', :path => '../../../node_modules/@capacitor/share'
  pod 'EbarooniCapacitorCalendar', :path => '../../../node_modules/@ebarooni/capacitor-calendar'
  pod 'MichaelwolzCameraPreviewLite', :path => '../../../node_modules/@michaelwolz/camera-preview-lite'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../../node_modules/@revenuecat/purchases-capacitor'
  pod 'CapacitorNativeSettings', :path => '../../../node_modules/capacitor-native-settings'
end

target 'App' do
  capacitor_pods
  # Add your Pods here

  # Firebase Crashlytics
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
